# Generated by Django 6.0.5 on 2026-05-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0003_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__name': 'master'}, related_name='services', to='beauty_salon.user'),
        ),
    ]
