# Generated by Django 6.0.5 on 2026-05-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0005_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
    ]
