# Generated by Django 6.0.5 on 2026-05-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0006_alter_notification_options_alter_notification_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='masters/', verbose_name='Фото мастера'),
        ),
    ]
