# Generated by Django 6.0.5 on 2026-06-01 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_salon', '0007_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='master',
            field=models.ForeignKey(blank=True, db_column='master_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_reviews', to='beauty_salon.user'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('master', 'Мастер'), ('salon', 'Салон')], default='master', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Опубликован'), ('hidden', 'Скрыт'), ('deleted', 'Удалён')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='appointment',
            field=models.ForeignKey(blank=True, db_column='appointment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beauty_salon.appointment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to='beauty_salon.user'),
        ),
    ]
